spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enable: true