version: '3'
services:
  todo-mariadb:
    container_name: todo-mariadb
    image: mariadb
    build:
      context: ./mariadb
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - todo-list
  todo-backend:
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - todo-list
    depends_on:
      - todo-mariadb
  todo-frontend:
    container_name: todo-frontend
    image: nginx
    build:
      context: ./frontend
    volumes:
      - ./frontend/web-ui-build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - todo-list
    depends_on:
      - todo-backend
networks:
  todo-list:
    driver: bridge